/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AIChatWidget: typeof import('./components/AIChatWidget.vue')['default']
    AIChatZone: typeof import('./components/AIChatZone.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    PDFExporter: typeof import('./components/PDFExporter.vue')['default']
    ProductDetailContent: typeof import('./components/ProductDetailContent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBox: typeof import('./components/SearchBox.vue')['default']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
  }
}
